# Generated by Django 2.2.2 on 2019-06-29 09:34

from django.db import migrations, models
import django.db.models.deletion
import skroc_url.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryURL', models.URLField()),
                ('shortURL', models.CharField(default=skroc_url.models.shortURL, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skroc_url.QueryURL')),
            ],
        ),
    ]
